// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  disciplines: [
    {
      type: 'category',
      label: '數學',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'mathematics' }],
    },
    {
      type: 'category',
      label: '土木工程',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'civil-engineering' }],
    },
    {
      type: 'category',
      label: '電腦科學',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'computer-science' }],
    },
  ],
  developments: [
    {
      type: 'category',
      label: '程式語言',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'programming-language' }],
    },
    {
      type: 'category',
      label: '設計模式',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'design-pattern' }],
    },
  ],
};

module.exports = sidebars;
