const sidebars = {
  // docs: [{ type: 'autogenerated', dirName: '.' }],
  ddia: [
    {
      type: 'html',
      value: '<img src="https://i.imgur.com/rOzjWjI.png" alt="Sponsor" />', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'Designing Data-Intensive Application',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'designing-data-intensive-application/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'designing-data-intensive-application',
        },
      ],
    },
  ],
};

module.exports = sidebars;
