const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],

  'es6-javascript-the-complete-developers-guide': [
    {
      type: 'category',
      label: "ES6 JavaScript: The Complete Developer's Guide",
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'es6-javascript-the-complete-developers-guide/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'es6-javascript-the-complete-developers-guide',
        },
      ],
    },
  ],
};

module.exports = sidebars;
